language: ruby
rvm:
 - "2.2.1"
# uncomment this line if your project needs to run something other than `rake`:
script: 
 - export COVERALLS_SERVICE_NAME=travis-ci
 - export COVERALLS_REPO_TOKEN=S2HDHzXMsi0lHwzAhGQPddSUGeXXcmVty
 - bundle exec rspec spec
